// Demo data — realistic fictional data for the interactive demo

export const DEMO_TRAINER = {
  name: 'Álvaro García',
  initials: 'AG',
  plan: 'Pro',
  stats: {
    activeClients: 14,
    todayAppointments: 3,
    newMessages: 5,
    monthRevenue: 2340,
    retention: 91,
    weekSessions: { completed: 8, total: 12 },
  },
  clients: [
    { id: 1, name: 'Ana Martínez',     initials: 'AM', colorClass: 'bg-brand-primary/20 text-brand-primary',      progress: 92, streak: 18, status: 'active' as const, lastSeen: 'hace 2h',     plan: 'Mensual 150€', goal: 'Pérdida de peso' },
    { id: 2, name: 'Carlos López',     initials: 'CL', colorClass: 'bg-semantic-info/20 text-semantic-info',       progress: 67, streak: 7,  status: 'active' as const, lastSeen: 'hoy',         plan: 'Mensual 150€', goal: 'Ganancia muscular' },
    { id: 3, name: 'María Fernández',  initials: 'MF', colorClass: 'bg-purple-500/20 text-purple-400',             progress: 84, streak: 14, status: 'active' as const, lastSeen: 'ayer',        plan: 'Mensual 120€', goal: 'Tonificación' },
    { id: 4, name: 'Pedro Ruiz',       initials: 'PR', colorClass: 'bg-semantic-warning/20 text-semantic-warning', progress: 31, streak: 0,  status: 'paused' as const, lastSeen: 'hace 5 días', plan: 'Mensual 150€', goal: 'Rendimiento' },
    { id: 5, name: 'Laura Torres',     initials: 'LT', colorClass: 'bg-pink-500/20 text-pink-400',                 progress: 78, streak: 21, status: 'active' as const, lastSeen: 'hace 1h',     plan: 'Mensual 180€', goal: 'Pérdida de peso' },
    { id: 6, name: 'Javier Morales',   initials: 'JM', colorClass: 'bg-cyan-500/20 text-cyan-400',                 progress: 55, streak: 4,  status: 'active' as const, lastSeen: 'hoy',         plan: 'Mensual 150€', goal: 'Rehabilitación' },
  ],
  todayAppointments: [
    { id: 1, client: 'Ana Martínez',    initials: 'AM', colorClass: 'bg-brand-primary/20 text-brand-primary',  time: '09:00', type: 'Presencial' as const, duration: 60 },
    { id: 2, client: 'Carlos López',    initials: 'CL', colorClass: 'bg-semantic-info/20 text-semantic-info',  time: '11:30', type: 'Online'     as const, duration: 45 },
    { id: 3, client: 'María Fernández', initials: 'MF', colorClass: 'bg-purple-500/20 text-purple-400',        time: '17:00', type: 'Presencial' as const, duration: 60 },
  ],
  recentActivity: [
    { client: 'Ana Martínez',    initials: 'AM', colorClass: 'bg-brand-primary/20 text-brand-primary', action: 'completó su rutina de hoy 💪',           time: 'hace 23 min' },
    { client: 'Laura Torres',    initials: 'LT', colorClass: 'bg-pink-500/20 text-pink-400',          action: '¡racha de 21 días! 🔥',                  time: 'hace 1h' },
    { client: 'Carlos López',    initials: 'CL', colorClass: 'bg-semantic-info/20 text-semantic-info', action: 'registró 78.2 kg (−0.6 kg) ⬇️',          time: 'hace 2h' },
    { client: 'María Fernández', initials: 'MF', colorClass: 'bg-purple-500/20 text-purple-400',      action: 'envió un mensaje nuevo 💬',              time: 'hace 3h' },
    { client: 'Javier Morales',  initials: 'JM', colorClass: 'bg-cyan-500/20 text-cyan-400',          action: 'completó el check-in semanal ✅',         time: 'hace 4h' },
  ],
  alerts: [
    { type: 'warning' as const, client: 'Pedro Ruiz',    message: 'lleva 5 días sin entrenar', action: 'Mandar mensaje', actionType: 'message' as const },
    { type: 'error'   as const, client: 'Javier Morales', message: 'pago del mes pendiente',   action: 'Ver facturas',   actionType: 'invoice' as const },
  ],
  revenueChart: [1680, 1920, 2100, 2280, 2100, 2340],
  months: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun'],
  routines: [
    {
      id: 1,
      name: 'Fuerza · Pecho y Tríceps',
      clients: 4,
      days: 'L · M · J',
      level: 'Intermedio',
      completion: 84,
      exercises: [
        { name: 'Press de banca', sets: 4, reps: 8,  rest: 90, notes: 'Agarre ancho' },
        { name: 'Aperturas inclinado', sets: 3, reps: 12, rest: 60, notes: null },
        { name: 'Fondos en paralelas', sets: 3, reps: 10, rest: 60, notes: null },
        { name: 'Extensión tríceps polea', sets: 3, reps: 15, rest: 45, notes: null },
        { name: 'Press francés', sets: 3, reps: 12, rest: 60, notes: 'Barra EZ' },
      ],
    },
    {
      id: 2,
      name: 'HIIT · Full Body',
      clients: 6,
      days: 'M · J · S',
      level: 'Avanzado',
      completion: 91,
      exercises: [
        { name: 'Burpees', sets: 4, reps: 10, rest: 30, notes: '30s trabajo / 30s descanso' },
        { name: 'Saltos al cajón', sets: 4, reps: 8, rest: 30, notes: null },
        { name: 'Mountain climbers', sets: 4, reps: 20, rest: 30, notes: null },
        { name: 'Kettlebell swing', sets: 4, reps: 15, rest: 45, notes: '16kg' },
      ],
    },
  ],
  messages: [
    { id: 1, client: 'Ana Martínez',    initials: 'AM', colorClass: 'bg-brand-primary/20 text-brand-primary', unread: true,  lastTime: 'hace 15min', preview: '¡Hoy me he sentido con más energía! 💪', thread: [
      { from: 'client' as const, text: '¡Buenos días Álvaro! Tengo una duda sobre el ejercicio de mañana.', time: '09:12' },
      { from: 'trainer' as const, text: 'Hola Ana, dime 😊', time: '09:15' },
      { from: 'client' as const, text: '¿El press de banca lo hago con barra o mancuernas?', time: '09:16' },
      { from: 'trainer' as const, text: 'Hoy con barra, la semana que viene con mancuernas para variar el estímulo.', time: '09:18' },
      { from: 'client' as const, text: '¡Hoy me he sentido con más energía! 💪', time: '11:40' },
    ]},
    { id: 2, client: 'Carlos López',    initials: 'CL', colorClass: 'bg-semantic-info/20 text-semantic-info',  unread: true,  lastTime: 'hace 2h',   preview: 'Mañana no puedo a las 11:30, ¿otro horario?', thread: [
      { from: 'client' as const, text: 'Mañana no puedo a las 11:30, ¿otro horario?', time: '10:05' },
    ]},
    { id: 3, client: 'María Fernández', initials: 'MF', colorClass: 'bg-purple-500/20 text-purple-400',         unread: false, lastTime: 'ayer',      preview: 'Perfecto, nos vemos el jueves', thread: [
      { from: 'trainer' as const, text: '¿Cómo fue la sesión de hoy?', time: '18:30' },
      { from: 'client' as const, text: 'Muy bien, me costó un poco el último ejercicio pero lo terminé.', time: '18:45' },
      { from: 'trainer' as const, text: '¡Perfecto! Eso es lo que queremos 💪', time: '18:47' },
      { from: 'client' as const, text: 'Perfecto, nos vemos el jueves', time: '18:50' },
    ]},
  ],
}

export const DEMO_CLIENT = {
  name: 'Ana Martínez',
  initials: 'AM',
  trainer: 'Álvaro García',
  streak: 18,
  longestStreak: 21,
  weightStart: 72.4,
  weightCurrent: 68.2,
  sessionsThisMonth: 14,
  goalCompletion: 78,
  nextAppointment: { date: 'Mañana', time: '09:00', type: 'Presencial' },
  todayRoutine: {
    name: 'Fuerza · Pecho y Tríceps',
    category: 'Fuerza',
    exercises: 5,
    duration: 45,
    completed: false,
    exercises_list: [
      { name: 'Press de banca', sets: 4, reps: 8,  weight: 50, completed: false },
      { name: 'Aperturas inclinado', sets: 3, reps: 12, weight: 14, completed: false },
      { name: 'Fondos en paralelas', sets: 3, reps: 10, weight: 0,  completed: false },
      { name: 'Extensión tríceps polea', sets: 3, reps: 15, weight: 20, completed: false },
      { name: 'Press francés', sets: 3, reps: 12, weight: 25, completed: false },
    ],
  },
  habits: [
    { id: 1, name: 'Beber 2L de agua', icon: '💧', completed: false, streak: 12 },
    { id: 2, name: 'Dormir 8 horas',   icon: '😴', completed: true,  streak: 5  },
    { id: 3, name: '10.000 pasos',     icon: '👟', completed: false, streak: 3  },
  ],
  progressLog: [
    { date: '18 Jun', weight: 68.2 },
    { date: '11 Jun', weight: 68.8 },
    { date: '4 Jun',  weight: 69.3 },
    { date: '28 May', weight: 70.1 },
    { date: '21 May', weight: 71.0 },
    { date: '14 May', weight: 71.6 },
    { date: '7 May',  weight: 72.0 },
    { date: '30 Abr', weight: 72.4 },
  ],
  achievements: [
    { id: 1, name: 'Primera semana',   icon: '🌟', unlocked: true,  date: '24 Abr' },
    { id: 2, name: '10 sesiones',      icon: '💪', unlocked: true,  date: '8 May' },
    { id: 3, name: 'Racha de 7 días',  icon: '🔥', unlocked: true,  date: '1 May' },
    { id: 4, name: 'Racha de 14 días', icon: '⚡', unlocked: true,  date: '15 May' },
    { id: 5, name: 'Racha de 21 días', icon: '🏆', unlocked: false, date: null },
    { id: 6, name: '5 kg perdidos',    icon: '⬇️', unlocked: false, date: null },
  ],
}
